### ISSUE TITLE
Remove verbose option on QuickSync Untar

### ISSUE THREAD

**Issue by XCBatman** [NeblioTeam/NEBL-Pi#5]
**Issue**: The addition of the `-v` to the QuickSync untar option is unnecessary and can slow down the untar

**Description**: Although minor, with large tar files using the -v can slow down the untar process. As the Neblio blockchain grows, this can result in a noticeable slowdown. 

**Recommendation**: Change the existing line in the NEBL-Pi-Installer.sh file:
FROM: `tar -zxvf temp.tar.gz`
TO: `tar -zxf temp.tar.gz`

**Comment by nebliodev** [comment]
Closing since we no longer tar quicksync files and download the mdb file directly.
